const API='https://soonsoon-bible-analytics.ppss10103s.chatgpt.site';
const $=s=>document.querySelector(s),el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const num=n=>Number(n||0).toLocaleString('zh-TW'),percent=(n,d)=>d?(n/d*100).toFixed(1)+'%':'—';
const day=(ms=Date.now())=>new Date(ms+8*3600000).toISOString().slice(0,10);
let key='',data=null,ga=null,currentRank='bible_search',range={},requestNo=0;
$('#start').max=$('#end').max=day();
function getRange(){const p=$('#period').value,today=day();let start=today,end=today;if(p==='yesterday')start=end=day(Date.now()-86400000);else if(/^\d+$/.test(p))start=day(Date.now()-(Number(p)-1)*86400000);else if(p==='year')start=today.slice(0,4)+'-01-01';else if(p==='all')start='2026-05-12';else if(p==='custom'){start=$('#start').value;end=$('#end').value;}return {start,end};}
async function fetchData(path){const response=await fetch(API+path+'?'+new URLSearchParams(range),{headers:{Authorization:'Bearer '+key},cache:'no-store'});if(response.status===401)throw Error('管理金鑰不正確，請重新輸入。');if(!response.ok)throw Error('統計暫時無法讀取，請稍後重試。');return response.json();}
$('#loginForm').onsubmit=async e=>{e.preventDefault();key=$('#key').value.trim();$('#loginStatus').textContent='正在驗證…';try{range=getRange();data=await fetchData('/api/stats');$('#key').value='';$('#login').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;$('#loginStatus').textContent='';await load();}catch(err){$('#loginStatus').textContent=err.message;key='';}};
$('#logout').onclick=()=>{key='';data=null;ga=null;$('#dashboard').hidden=true;$('#login').hidden=false;$('#logout').hidden=true;$('#cards').replaceChildren();$('#rankings').replaceChildren();$('#audience').replaceChildren();};
$('#period').onchange=()=>{$('#customDates').hidden=$('#period').value!=='custom';if($('#period').value!=='custom')load();else{$('#start').value=range.start;$('#end').value=range.end;}};
$('#applyDates').onclick=load;$('#refresh').onclick=load;$('#bucket').onchange=drawTrend;
for(const b of document.querySelectorAll('[data-rank]')){b.onclick=()=>{currentRank=b.dataset.rank;document.querySelectorAll('[data-rank]').forEach(x=>{x.setAttribute('aria-selected',x===b);x.tabIndex=x===b?0:-1;});drawRank();};b.tabIndex=b.getAttribute('aria-selected')==='true'?0:-1;b.onkeydown=e=>{const list=[...document.querySelectorAll('[data-rank]')],i=list.indexOf(b);if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const target=e.key==='Home'?list[0]:e.key==='End'?list.at(-1):list[(i+(e.key==='ArrowRight'?1:list.length-1))%list.length];target.focus();target.click();}};}
async function load(){
  range=getRange();if(!range.start||!range.end||range.start>range.end||range.end>day()){$('#freshness').textContent='請選擇有效日期，結束日期不能超過今天。';return;}
  const id=++requestNo;$('#freshness').textContent='正在更新統計…';$('#dateLabel').textContent=range.start+' — '+range.end;$('#refresh').disabled=true;ga=null;
  try{data=await fetchData('/api/stats');if(id!==requestNo)return;drawCards();drawTrend();drawRank();$('#freshness').textContent='更新於 '+new Date(data.updatedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false})+' · 台北時間';$('#gaStatus').textContent='GA4 使用者與來源資料讀取中…';$('#audience').replaceChildren(el('p','muted','正在讀取 GA4…'));try{const value=await fetchData('/api/ga4');if(id!==requestNo)return;ga=value;drawCards();drawAudience();$('#gaStatus').textContent=ga.configured?'使用者來自 GA4，今日資料仍會補入。精確操作統計自 '+(data.firstDay||'新版上線')+' 起累積。':'GA4 事件已沿用原站設定；管理報表的服務帳戶尚未連接。';}catch(err){$('#gaStatus').textContent='GA4 報表暫時無法更新；精確搜尋與複製統計可正常查閱。';$('#audience').replaceChildren(el('p','muted','稍後重新整理即可重試 GA4。'));}}
  catch(err){$('#freshness').textContent=err.message;}finally{if(id===requestNo)$('#refresh').disabled=false;}
}
function drawCards(){const s=data.summary,searches=(s.bible_search||0)+(s.keyword_search||0),copies=(s.verse_copy||0)+(s.multi_verse_copy||0),pending=data.pending.reduce((n,r)=>n+r.value,0);const cards=[['今天使用者',ga?.configured?num(ga.users.today):'—','GA4 · 今日'],['近 7 天使用者',ga?.configured?num(ga.users.week):'—','GA4 · 期間去重'],['近 30 天使用者',ga?.configured?num(ga.users.month):'—','GA4 · 期間去重'],['搜尋次數',num(searches),`經文 ${num(s.bible_search)} · 關鍵字 ${num(s.keyword_search)}`],['複製次數',num(copies),`共複製 ${num(s.copied_verses)} 節`],['搜尋後複製率',percent(s.search_converted||0,searches),`${num(s.search_converted)} 次搜尋後有複製`],['無結果搜尋',num(s.zero_result),'可在下方查看搜尋內容'],['搜尋格式錯誤',num(s.search_error),'不含在有效格式搜尋次數內'],['搜尋後未操作',num(Math.max(0,searches-(s.search_engaged||0)-pending)),'已排除最近 30 分鐘尚未完成的搜尋']];const c=$('#cards');c.replaceChildren();for(const [label,value,note] of cards){const m=el('div','metric');m.append(el('div','label',label),el('div','value',value),el('small','',note));c.append(m);}}
function table(headers,rows){const t=el('table'),thead=el('thead'),tr=el('tr');headers.forEach((h,i)=>tr.append(el('th',i>0?'number':'',h)));thead.append(tr);t.append(thead);const body=el('tbody');for(const row of rows){const tr=el('tr');row.forEach((v,i)=>{const td=el('td',i>0?'number':'');td.append(v instanceof Node?v:document.createTextNode(String(v)));tr.append(td);});body.append(tr);}t.append(body);return t;}
function drawRank(){if(!data)return;const ranks=data.rankings[currentRank]||[],search=['bible_search','keyword_search'].includes(currentRank),note=$('#rankNote');note.textContent=search?'同義經文格式已合併。複製為這些搜尋後的成功複製操作。':currentRank==='abandoned'?'超過 30 分鐘未選取、複製或載入更多；可能只閱讀，並不代表搜尋失敗。':currentRank==='copy_verse'?'每次複製中的各節各計一次，包含多節／整段複製。':currentRank==='search_error'?'數字已轉成 #，以格式模式整理；排除疑似個資。':currentRank==='copy_passage'?'每次成功複製的一整段經文，計一次。':'依所選期間的操作次數排序。';const c=$('#rankings');c.replaceChildren();if(!ranks.length){c.append(el('p','empty-data','這段期間尚無資料。'));return;}const rows=ranks.map((r,i)=>{const label=el('span','',`${i+1}.　${r.label}`),detail=data.details.find(d=>d.key===r.key);return search?[label,num(r.value),num(detail?.copies),percent(detail?.converted||0,r.value)]:[label,num(r.value)];});c.append(table(search?['搜尋內容','搜尋','複製','複製率']:[currentRank==='search_error'?'輸入格式':'內容','次數'],rows));}
function trendData(){const map=new Map();for(let date=range.start;date<=range.end;date=new Date(Date.parse(date)+86400000).toISOString().slice(0,10))map.set(date,{date,searches:0,copies:0});for(const r of data.series){const row=map.get(r.day);if(!row)continue;if(['bible_search','keyword_search'].includes(r.type))row.searches+=r.value;if(['verse_copy','multi_verse_copy'].includes(r.type))row.copies+=r.value;}const bucket=$('#bucket').value;if(bucket==='day')return [...map.values()];const grouped=new Map();for(const row of map.values()){let date=row.date;if(bucket==='month')date=date.slice(0,7);else{const dt=new Date(date);dt.setUTCDate(dt.getUTCDate()-((dt.getUTCDay()+6)%7));date=dt.toISOString().slice(0,10);}if(!grouped.has(date))grouped.set(date,{date,searches:0,copies:0});grouped.get(date).searches+=row.searches;grouped.get(date).copies+=row.copies;}return [...grouped.values()];}
function drawTrend(){if(!data)return;const rows=trendData(),c=$('#trend');c.replaceChildren();$('#trendTable').replaceChildren(table(['日期','搜尋','複製'],rows.map(r=>[r.date,num(r.searches),num(r.copies)])));if(!rows.some(r=>r.searches||r.copies)){c.append(el('p','empty-data','這段期間還沒有搜尋或複製紀錄。'));return;}const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 900 230');svg.setAttribute('role','img');svg.setAttribute('aria-label','所選期間的搜尋及複製操作趨勢；完整數據可在下方展開。');svg.classList.add('chart');const max=Math.max(1,...rows.flatMap(r=>[r.searches,r.copies]));const x=i=>48+i*(832/Math.max(1,rows.length-1)),y=v=>185-v/max*157;const add=(tag,attrs,text)=>{const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text!==undefined)n.textContent=text;svg.append(n);return n;};for(let i=0;i<=3;i++){const v=max*i/3;add('line',{x1:48,x2:882,y1:y(v),y2:y(v),class:'grid'});add('text',{x:38,y:y(v)+4,'text-anchor':'end'},num(Math.round(v)));}for(const [key,cls] of [['searches','search-line'],['copies','copy-line']]){add('polyline',{points:rows.map((r,i)=>x(i)+','+y(r[key])).join(' '),class:cls});if(rows.length===1)add('circle',{cx:x(0),cy:y(rows[0][key]),r:4,fill:key==='searches'?'var(--blue)':'#24a080'});}const idx=[...new Set([0,Math.floor((rows.length-1)/2),rows.length-1])];idx.forEach(i=>add('text',{x:x(i),y:215,'text-anchor':i===0?'start':i===rows.length-1?'end':'middle'},rows[i].date));c.append(svg);const legend=el('div','chart-legend');for(const [cls,text] of [['','搜尋'],['copy','複製']]){const span=el('span');span.append(el('i','legend-dot '+cls),document.createTextNode(text));legend.append(span);}c.append(legend);}
function drawAudience(){const c=$('#audience');c.replaceChildren();if(!ga?.configured){c.append(el('p','muted','連接既有 GA4 服務帳戶後，即可讀取使用者、Sessions、來源及裝置。'));return;}const s=ga.summary?.rows[0]||{},overview=el('div','audience-overview');for(const [label,value] of [['期間使用者',num(s.totalUsers)],['Sessions',num(s.sessions)],['互動工作階段',num(s.engagedSessions)],['每次工作階段互動',num(Math.round((s.userEngagementDuration||0)/(s.sessions||1)))+' 秒']]){const span=el('span','muted',label+'　');span.append(el('strong','',value));overview.append(span);}c.append(overview);for(const [title,list,dimension,metric] of [['使用裝置',ga.devices?.rows,'deviceCategory','totalUsers'],['流量來源',ga.sources?.rows,'sessionDefaultChannelGroup','sessions'],['新訪客 / 回訪',ga.returning?.rows,'newVsReturning','totalUsers']]){const d=el('div');d.append(el('h3','',title));const ul=el('ul');const translate={mobile:'手機',desktop:'電腦',tablet:'平板',new:'新訪客',returning:'回訪者','(not set)':'未提供','Direct':'直接流量','Organic Search':'自然搜尋','Organic Social':'社群','Referral':'其他網站','Unassigned':'未分類'};for(const r of (list||[]).sort((a,b)=>b[metric]-a[metric]).slice(0,10)){const li=el('li');li.append(el('span','',translate[r[dimension]]||r[dimension]),el('strong','',num(r[metric])));ul.append(li);}d.append(ul);c.append(d);}}
