const $=id=>document.getElementById(id),data=window.SCORES,audio=$('audio');let filter='all',page=1,current=null,queue=[],request=0;let ranking={status:'idle',rows:[],updatedAt:null},rankingRequest=0;const size=12;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const buy=s=>'https://www.pbooks.com.tw/products/'+s.id.toLowerCase();const source=s=>'https://cdn.jsdelivr.net/gh/philemon86/tjc-music@main/'+(s.s||s.id)+'.mp3';const time=n=>Number.isFinite(n)?Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0'):'0:00';
[...new Set(data.map(s=>s.c))].sort((a,b)=>a.localeCompare(b,'zh-Hant')).forEach(s=>$('author').add(new Option(s,s)));[...new Set(data.map(s=>+s.pr))].sort((a,b)=>a-b).forEach(s=>$('price').add(new Option('NT$ '+s,s)));
function filtered(){const terms=PhilemonLanguage.normalize($('search').value).trim().split(/\s+/).filter(Boolean);return data.filter(s=>terms.every(t=>[s.n,s.id,s.c,s.l].some(v=>PhilemonLanguage.normalize(v).includes(t)))&&(filter==='all'||s.v==='P')&&(filter!=='ranking'||ranking.rows.some(row=>row.id===s.id))&&(!$('author').value||s.c===$('author').value)&&(!$('price').value||s.pr===$('price').value)).sort((a,b)=>filter==='ranking'?(ranking.rows.find(r=>r.id===b.id)?.count||0)-(ranking.rows.find(r=>r.id===a.id)?.count||0)||a.id.localeCompare(b.id,undefined,{numeric:true}):$('sort').value==='price'?a.pr-b.pr:$('sort').value==='pages'?a.pg-b.pg:a.id.localeCompare(b.id,undefined,{numeric:true}));}
function render(){const list=filtered(),total=Math.max(1,Math.ceil(list.length/size));page=Math.min(page,total);$('count').textContent='共 '+list.length+' 首曲目';$('rankingInfo').hidden=filter!=='ranking';$('sort').disabled=filter==='ranking';document.querySelector('.table-head').children[3].textContent=filter==='ranking'?'試聽次數':'頁數';$('empty').hidden=!!list.length;$('reset').hidden=!($('search').value||$('author').value||$('price').value||filter!=='all');$('clearSearch').hidden=!$('search').value;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===filter);b.setAttribute('aria-pressed',b.dataset.filter===filter)});$('songs').innerHTML=list.slice((page-1)*size,page*size).map(s=>`<article class="song ${current?.id===s.id?'current':''}">${s.v==='P'?`<button class="play" data-play="${s.id}" aria-label="${current?.id===s.id&&!audio.paused?'暫停':'播放'} ${esc(s.n)}">${current?.id===s.id&&!audio.paused?'Ⅱ':'▶'}</button>`:'<span class="unavailable">無試聽</span>'}<div><button class="title" data-detail="${s.id}">${esc(s.n)}</button><span class="code">${filter==='ranking'?'#'+(ranking.rows.findIndex(r=>r.id===s.id)+1)+' · ':''}${s.id}${filter==='ranking'?'<span class="mobile-plays"> · '+ranking.rows.find(r=>r.id===s.id).count.toLocaleString()+' 次試聽</span>':''}</span></div><div class="author">${esc(s.c)}</div><span class="pages">${filter==='ranking'?ranking.rows.find(r=>r.id===s.id).count.toLocaleString()+' 次':s.pg+' 頁'}</span><span class="price"><small>NT$</small>${s.pr}</span><a class="buy" href="${buy(s)}" target="_blank" rel="noopener" aria-label="選購 ${esc(s.n)} 樂譜">商品頁 ↗</a></article>`).join('');$('range').textContent=list.length?`${(page-1)*size+1}–${Math.min(page*size,list.length)} / ${list.length} 首`:'0 首';$('pageNumber').textContent=page+' / '+total;$('prevPage').disabled=page===1;$('nextPage').disabled=page===total;renderRankingStatus(list.length);sync();}
function sync(){$('toggle').textContent=audio.paused?'▶':'Ⅱ';$('toggle').setAttribute('aria-label',audio.paused?'播放':'暫停');['toggle','previous','next','nowTitle'].forEach(id=>$(id).disabled=!current);if(current){$('nowTitle').textContent=current.n;$('nowSub').textContent=current.id+' · '+current.c;$('playerBuy').hidden=false;$('playerBuy').href=buy(current)}const detailPlay=document.querySelector('[data-detail-play]');if(detailPlay)detailPlay.textContent=current?.id===detailPlay.dataset.detailPlay&&!audio.paused?'Ⅱ 暫停試聽':'▶ 試聽歌曲';}
async function play(s,newQueue=true){if(s.v!=='P')return;if(current?.id===s.id){if(!audio.paused){audio.pause();return}}else{if(newQueue)queue=filtered().filter(v=>v.v==='P');if(!queue.some(v=>v.id===s.id))queue=[s];current=s;PhilemonAnalytics.select(s);audio.src=source(s);$('elapsed').textContent='0:00';$('duration').textContent='0:00';$('seek').value=0;}if(audio.ended){PhilemonAnalytics.select(s);audio.currentTime=0;}const token=++request;$('playerStatus').textContent='正在載入試聽…';render();try{await audio.play();if(token===request)$('playerStatus').textContent=''}catch(e){if(token===request&&e.name!=='AbortError')$('playerStatus').textContent='音訊暫時無法載入，請按播放重試。'}sync();}
function step(direction){if(!current||!queue.length)return;let i=queue.findIndex(s=>s.id===current.id);play(queue[(i+direction+queue.length)%queue.length],false)}function detail(s){$('detailContent').innerHTML=`<span class="eyebrow">SCORE / ${s.id}</span><h2>${esc(s.n)}</h2><dl><dt>作曲</dt><dd>${esc(s.c)}</dd><dt>作詞</dt><dd>${esc(s.l)}</dd><dt>樂譜頁數</dt><dd>${s.pg} 頁</dd><dt>樂譜價格</dt><dd>NT$ ${s.pr}</dd></dl>${s.s?'<p class="note">此編制使用原站提供的共用試聽音訊（'+esc(s.s)+'）。</p>':''}<div class="detail-actions">${s.v==='P'?`<button data-detail-play="${s.id}">▶ 試聽歌曲</button>`:'<span>目前無試聽音訊</span>'}<a href="${buy(s)}" target="_blank" rel="noopener">前往商品頁 ↗</a></div><p class="note">價格依原站目錄顯示，購買資訊以商品頁為準。</p>`;$('details').showModal();sync()}
$('songs').onclick=e=>{const p=e.target.closest('[data-play]'),d=e.target.closest('[data-detail]');if(p)play(data.find(s=>s.id===p.dataset.play));if(d)detail(data.find(s=>s.id===d.dataset.detail));};$('details').onclick=e=>{if(e.target.closest('.close')||e.target===$('details'))$('details').close();const p=e.target.closest('[data-detail-play]');if(p)play(data.find(s=>s.id===p.dataset.detailPlay))};$('nowTitle').onclick=()=>current&&detail(current);$('toggle').onclick=()=>current&&play(current,false);$('previous').onclick=()=>step(-1);$('next').onclick=()=>step(1);audio.volume=.8;audio.onplay=audio.onpause=()=>render();audio.onplaying=()=>{$('playerStatus').textContent=''};audio.onwaiting=()=>{$('playerStatus').textContent='音訊緩衝中…'};audio.onerror=()=>{$('playerStatus').textContent='音訊暫時無法載入，請按播放重試。';sync()};audio.onended=()=>{const i=queue.findIndex(s=>s.id===current?.id);if(i>=0&&i<queue.length-1)play(queue[i+1],false);else render()};audio.ontimeupdate=()=>{PhilemonAnalytics.count(audio);$('elapsed').textContent=time(audio.currentTime);$('seek').value=audio.duration?audio.currentTime/audio.duration*100:0};audio.onloadedmetadata=()=>{$('duration').textContent=time(audio.duration);$('seek').disabled=!Number.isFinite(audio.duration)};$('seek').oninput=()=>{if(Number.isFinite(audio.duration))audio.currentTime=Number($('seek').value)*audio.duration/100};$('volume').oninput=()=>{audio.volume=+$('volume').value;audio.muted=false;$('mute').setAttribute('aria-label','靜音')};$('mute').onclick=()=>{audio.muted=!audio.muted;$('mute').setAttribute('aria-label',audio.muted?'取消靜音':'靜音');$('mute').textContent=audio.muted?'×':'♪'};
for(const id of ['search','author','price','sort'])$(id).addEventListener(id==='search'?'input':'change',()=>{page=1;render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;page=1;render();if(filter==='ranking')loadRanking()});function reset(){filter='all';page=1;['search','author','price'].forEach(id=>$(id).value='');$('sort').value='code';render()}$('reset').onclick=$('emptyReset').onclick=reset;$('clearSearch').onclick=()=>{$('search').value='';page=1;render();$('search').focus()};$('prevPage').onclick=()=>{page--;render();$('library').scrollIntoView()};$('nextPage').onclick=()=>{page++;render();$('library').scrollIntoView()};render();

function renderRankingStatus(count){
 const isRanking=filter==='ranking',empty=$('empty');
 if(!isRanking){empty.querySelector('h3').textContent='還沒有找到這首歌';empty.querySelector('p').textContent='試試較短的歌名、作者姓名或歌曲代碼。';return;}
 const descriptions={idle:'正在取得試聽排行…',loading:'正在取得試聽排行…',not_configured:'',unavailable:'暫時無法取得排行資料，請稍後重試。'};
 $('rankingStatus').textContent=descriptions[ranking.status]||(ranking.updatedAt?'資料更新：'+new Date(ranking.updatedAt).toLocaleString('zh-TW')+' · 統計至昨日，GA4 報表非即時更新':'');
 if(!count){empty.hidden=false;empty.querySelector('h3').textContent=ranking.status==='ready'?(ranking.rows.length?'沒有符合篩選的排行曲目':'這段期間尚無試聽紀錄'):(ranking.status==='loading'||ranking.status==='idle'?'正在載入排行':'試聽排行準備中');empty.querySelector('p').textContent=ranking.status==='ready'?'可以調整篩選或統計期間，或回到全部曲目探索。':'你仍可以搜尋、試聽與選購全部曲目。';}
}
async function loadRanking(){
 const token=++rankingRequest;ranking={status:'loading',rows:[],updatedAt:null};render();
 try{const response=await fetch('./rankings.json',{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('report unavailable');const snapshot=await response.json();const body=snapshot.periods?.[$('rankingPeriod').value]||snapshot;if(token!==rankingRequest)return;if(!['ready','not_configured','unavailable'].includes(body.status)||!Array.isArray(body.rows))throw Error('invalid report');const known=new Set(data.map(s=>s.id));document.querySelector('[data-filter=ranking]').hidden=body.status!=='ready';ranking={status:body.status,updatedAt:body.updatedAt,rows:body.rows.filter(r=>known.has(r.id)&&Number.isSafeInteger(r.count)&&r.count>0).sort((a,b)=>b.count-a.count||a.id.localeCompare(b.id,undefined,{numeric:true}))};}catch{if(token!==rankingRequest)return;ranking={status:'unavailable',rows:[],updatedAt:null};}
 if(filter==='ranking'&&ranking.status!=='ready'){filter='all';page=1;}render();
}
$('rankingPeriod').onchange=()=>{page=1;loadRanking()};

loadRanking();
